/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Mintlify Design Tokens
        "base-default": "var(--base-default)",
        "base-invert": "var(--base-invert)",
        "base-white": "#ffffff",
        "base-black": "#0a0b0f",
        "background-primary": "var(--background-primary)",
        "background-secondary": "var(--background-secondary)",
        "background-tertiary": "var(--background-tertiary)",
        "background-tertiary-invert": "var(--background-tertiary-invert)",
        "background-transparent": "var(--background-transparent)",
        "background-transparent-invert": "var(--background-transparent-invert)",
        "foreground-primary": "var(--foreground-primary)",
        "foreground-invert": "var(--foreground-invert)",
        "foreground-secondary": "var(--foreground-secondary)",
        "foreground-tertiary": "var(--foreground-tertiary)",
        "foreground-muted": "var(--foreground-muted)",
        "border-line": "var(--border-line)",
        "border-primary": "var(--border-primary)",
        "border-secondary": "var(--border-secondary)",
        "border-tertiary": "var(--border-tertiary)",
        "border-muted": "var(--border-muted)",
        "border-transparent": "var(--border-transparent)",
        "brand-base": "var(--brand-base)",
        "brand-vivid": "var(--brand-vivid)",
        "brand-8": "var(--brand-8)",
        "brand-10": "var(--brand-10)",
        "brand-20": "var(--brand-20)",
        error: "var(--error)",

        // Compatibility Aliases
        background: "var(--background-primary)",
        border: "var(--border-line)",
        surface: {
          50: "var(--background-tertiary)",
          100: "var(--background-secondary)",
          200: "var(--background-primary)",
          300: "var(--background-primary)",
        },
        brand: {
          50: "var(--brand-8)",
          100: "var(--brand-10)",
          200: "var(--brand-20)",
          500: "var(--brand-base)",
          600: "var(--brand-vivid)",
          700: "var(--brand-base)",
        },
        status: {
          pass: "var(--brand-base)",
          fail: "var(--error)",
          review: "#F59E0B",
          info: "#0EA5E9",
        },
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["Geist Mono", "ui-monospace", "SFMono-Regular", "monospace"],
        serif: ["ABC Arizona Flare", "Georgia", "serif"],
        paper: ["Paper Mono", "ui-monospace", "monospace"],
      },
      boxShadow: {
        "button-sm": "var(--shadow-button-sm)",
        "drop-sm": "var(--shadow-drop-sm)",
        "drop-md": "var(--shadow-drop-md)",
        "feature-card": "var(--shadow-feature-card)",
        "navbar-bg": "var(--shadow-navbar-bg)",
        "editor-tooltip": "var(--shadow-editor-tooltip)",
      },
      transitionTimingFunction: {
        "out-soft": "var(--ease-out-soft)",
        "out-expo": "var(--ease-out-expo)",
        "in-out-smooth": "var(--ease-in-out-smooth)",
        "out-strong": "var(--ease-out-strong)",
        "in-out-strong": "var(--ease-in-out-strong)",
      },
    },
  },
  plugins: [],
};
